[KK-0005]: :lipstick: Modified README.md file
kinga-kus/Blood-Donation pull request #5
Opened 2022-12-21 20:21 UTC by kinga-kus

In this PR, I have modified a view of README.md file. I have added important information and make it look cleaner.

2022-12-21 20:42 UTC, adam-kostuch requested changes
Although the file itself looks good, please remember to add some screenshots here once the project gets bigger.

And please before merging remove the files that doesn't belong here ❌

2022-12-21 20:42 UTC, adam-kostuch commented on README.md
> +## Blood Donation <img width="10%" src="./src/assets/logo.png" alt="Logo" />
I think that it would look better with the smaller logo. It kinda looks strange here 😃

2022-12-21 20:51 UTC, kinga-kus commented on README.md
> +## Blood Donation <img width="10%" src="./src/assets/logo.png" alt="Logo" />
Yes, in the nearest future I'll add some screenshoots. The smaller logo means it should be for example 5% ?

2022-12-22 20:00 UTC, adam-kostuch commented on README.md
> +## Blood Donation <img width="10%" src="./src/assets/logo.png" alt="Logo" />
Can't tell you what it looks like in 5%, but that would probably fit much better for sure!

2022-12-22 22:01 UTC, adam-kostuch requested changes
The README is looking 🔥 

But there are still 4 more unnecessary files changed in this PR, please delete them before merging. See this [thread](https://stackoverflow.com/a/44355701) for help.

2022-12-23 21:19 UTC, adam-kostuch approved these changes
Well done!!!! 🔥

2022-12-23 21:22 UTC, merged